<?php
return [
    'section_title' => 'Speakers at the Conference',
    'coming_soon' => 'Coming soon...',
    'details' => 'Details',
    'program' => [
        'toggle_label' => 'Program of the FTFL Conference',
        'schedule' => [
            ['time' => '09:15–10:00', 'title' => 'Registration'],
            ['time' => '10:00–10:05', 'title' => 'Rector\'s welcome address', 'speaker' => 'Krisztina Zimányi – Rector, Dennis Gabor University'],
            ['time' => '10:05–11:45', 'title' => 'Plenary sessions'],
        ],
        'plenary_talks' => [
            ['time' => '10:05–10:30', 'speaker' => 'Krisztina Zimányi – Rita Ősz', 'role' => 'Associate Professor – Rector', 'institution' => 'Dennis Gabor University',                          'title' => 'Same Platform, Different Journeys: Talent, Mass and Micro-learning'],
            ['time' => '10:30–10:55', 'speaker' => 'Päivi Häkkinen',                   'role' => 'Professor',                    'institution' => 'University of Jyväskylä, Finland',                 'title' => 'The Future of Learning and Collaboration in the Age of AI'],
            ['time' => '10:55–11:20', 'speaker' => 'Rikke Toft Nørgård',               'role' => 'Associate Professor',          'institution' => 'Danish School of Education, Aarhus University',   'title' => 'Between imagination and innovation: envisioning and engaging the future with hopepunk higher education'],
            ['time' => '11:20–11:45', 'speaker' => 'Márta Takács',                     'role' => 'Full University Professor',    'institution' => 'Hungarian Language Teacher Training Faculty, Subotica', 'title' => 'AI × Education: Everywhere, at Every Level – From Everyday Tools to Transformative Innovation in Learning'],
        ],
        'schedule_after' => [
            ['time' => '12:10–13:00', 'title' => 'Lunch break'],
            ['time' => '13:00–13:10', 'title' => 'Closing of the Gábor Dénes Memorial Year – Ferenc Dietz and Zsolt Fülöp'],
            ['time' => '13:10–17:30', 'title' => 'Section presentations (Coffee break: 15:20–15:50)'],
        ],
        'sections_label' => 'Section Presentations and Round Table Discussions',
        'sections' => [
            [
                'number'    => 1,
                'title'     => 'Horizon',
                'moderator' => 'Natália Kiss, Tomas Dragon',
                'room'      => 'Gábor Dénes Lecture Hall',
                'speakers'  => [
                    ['time' => '13:10–13:30', 'name' => 'Lucie Bryndova',           'role' => '', 'institution' => '', 'talk_title' => 'Assessing computational thinking in schools: Is it even possible to test the mind?'],
                    ['time' => '13:30–13:50', 'name' => 'Asmi Rusmanayanti',         'role' => '', 'institution' => '', 'talk_title' => 'Building Digital Competence for the Future of Learning: Insights from Pre-service and In-service EFL Teachers in Indonesia'],
                    ['time' => '13:50–14:10', 'name' => 'Péter Gyarmati',  'role' => '', 'institution' => '', 'talk_title' => 'Thoughts on Artificial Intelligence for Teachers'],
                    ['time' => '14:10–14:30', 'name' => 'László Murai',              'role' => '', 'institution' => '', 'talk_title' => 'We are EENJOY: Demonstrating ELTE\'s Experience-Based Platform for First-Year Induction with ARG Elements'],
                    ['time' => '14:30–14:50', 'name' => 'Veronika Csilla Derecskey', 'role' => '', 'institution' => '', 'talk_title' => 'Teacher Burnout and Re-Engagement in Hungarian Secondary EFL Education in Digitally Changing Educational Contexts'],
                    ['time' => '14:50–15:20', 'name' => 'Virág Vasas',               'role' => '', 'institution' => '', 'talk_title' => 'Breaking the „silent coder" stereotype: Information synthesis and professional visibility through elevator pitches in ICT education'],
                    ['time' => '15:20–15:50', 'name' => 'Coffee break', 'break' => true],
                    ['time' => '15:50–16:10', 'name' => 'Gergely Kovács',            'role' => '', 'institution' => '', 'talk_title' => 'Teaching Beyond Reality: AI Avatars, Virtual Campuses and the Next Generation of Education'],
                    ['time' => '16:10–16:30', 'name' => 'Attila M. Wind',            'role' => '', 'institution' => '', 'talk_title' => 'Linguistic Characteristics of AI-Generated and Human-Produced Texts'],
                    ['time' => '16:30–16:50', 'name' => 'Dorota Czajkowska',         'role' => '', 'institution' => '', 'talk_title' => 'From Data to Understanding: Using Artificial Intelligence and Real-Time Economic Data in Public Finance and Economics Education', 'online' => true],
                    ['time' => '16:50–17:10', 'name' => 'Emmanuel Abruquah',         'role' => '', 'institution' => '', 'talk_title' => 'Human-in-the-Loop Communication: Repositioning Communication Pedagogy in AI-Driven Education', 'online' => true],
                    ['time' => '17:10–17:30', 'name' => 'Serbakov-Kovács Emese',   'role' => '', 'institution' => '', 'talk_title' => 'Artificial Intelligence in Language Teaching: Opportunities, Challenges, and Future Perspectives', 'online' => true],
                ],
            ],
            [
                'number'    => 2,
                'title'     => 'Nexus',
                'moderator' => 'Krisztina Zimányi',
                'room'      => 'Nemes Tihamér Room',
                'speakers'  => [
                    ['time' => '13:10–13:30', 'name' => 'Fodor Andrea-Nagy Enikő – Molnár György',                             'role' => '', 'institution' => '', 'talk_title' => 'A tanulás lehetőségeinek átalakulása digitálisan közvetített felsőoktatási környezetekben'],
                    ['time' => '13:30–13:50', 'name' => 'Buda András',                                                          'role' => '', 'institution' => '', 'talk_title' => 'Artificial intelligence and teachers in Debrecen', 'online' => true],
                    ['time' => '13:50–14:10', 'name' => 'Ollé János',                                                           'role' => '', 'institution' => '', 'talk_title' => 'Mesterséges intelligencia oktatástervezési munkafolyamatokban való felhasználásának kompetenciacsökkentő hatása'],
                    ['time' => '14:10–14:30', 'name' => 'Kocsó Edina',                                                          'role' => '', 'institution' => '', 'talk_title' => 'Tanulási környezet és lemorzsolódás – hallgatói percepciók egy intézményi vizsgálatban'],
                    ['time' => '14:30–14:50', 'name' => 'Papp-Danka Adrienn – Csikós Ádám Valentin – Jaczina Fanni – Tóth Katalin', 'role' => '', 'institution' => '', 'talk_title' => 'Digitális kompetenciák longitudinális vizsgálata a felsőoktatásban'],
                    ['time' => '14:50–15:20', 'name' => 'Tóth Renáta',                                                          'role' => '', 'institution' => '', 'talk_title' => 'A generatív mesterséges intelligencia rejtett használata az általános iskolában. Eltérések a tanulói használat és a pedagógusi észlelés között.'],
                    ['time' => '15:20–15:50', 'name' => 'Coffee break', 'break' => true],
                    ['time' => '15:50–16:10', 'name' => 'Szontagh Pál Iván',                                         'role' => '', 'institution' => '', 'talk_title' => 'Felsőoktatás-pedagógiai kihívások a tömegesedő felsőoktatás korában'],
                    ['time' => '16:10–16:30', 'name' => 'Ladányi-Mészáros Judit',                                               'role' => '', 'institution' => '', 'talk_title' => 'A szociálpedagógia oktatástámogató szerepe a kortárs bántalmazás megelőzésében'],
                    ['time' => '16:30–16:50', 'name' => 'Molnárné László Andrea',                                           'role' => '', 'institution' => '', 'talk_title' => 'Mesterséges intelligencia mint hitéleti képzés: egy új interdiszciplináris modell kialakítása és tapasztalatai'],
                    ['time' => '16:50–17:10', 'name' => 'Kapusi Vanessza',                                                      'role' => '', 'institution' => '', 'talk_title' => 'Multimodális tanulási környezetek affektív hatásai hátrányos helyzetű tanulóknál', 'online' => true],
                    ['time' => '17:10–17:30', 'name' => 'Matlári Andrea',                                                       'role' => '', 'institution' => '', 'talk_title' => 'Az automatikus visszacsatolás szerepe a tanulásszabályozó döntésekben online tanulási környezetben'],
                ],
            ],
            [
                'number'    => 3,
                'title'     => 'Synergy',
                'moderator' => 'Rita Ősz',
                'room'      => 'Training Room',
                'speakers'  => [
                    ['time' => '13:10–13:30', 'name' => 'Kraszkó Zita',                          'role' => '', 'institution' => '', 'talk_title' => 'Beszéd és improvizáció – kreativitásfejlesztés és kommunikációs tréning a mesterséges intelligencia korában'],
                    ['time' => '13:30–13:50', 'name' => 'Korpics Márta Katalin – Méhes Tamás',   'role' => '', 'institution' => '', 'talk_title' => 'Az MI mint pedagógiai erőforrás: digitális kompetencia, oktatói szerepek és intézményi felelősség a felsőoktatásban'],
                    ['time' => '13:50–14:10', 'name' => 'Varga István',                           'role' => '', 'institution' => '', 'talk_title' => 'A szociálpedagógia átalakulása a digitális korszakban'],
                    ['time' => '14:10–14:30', 'name' => 'Papp Éva – Varga Tamás',                 'role' => '', 'institution' => '', 'talk_title' => 'Digitális ugródeszka: Komplex támogatási rendszer a Moodle alapú oktatáshoz'],
                    ['time' => '14:30–14:50', 'name' => 'Kis-Torma Olívia',                       'role' => '', 'institution' => '', 'talk_title' => 'Az algoritmikus tudatosság és a kritikai gondolkodás fejlesztése a virtuális entitások korában'],
                    ['time' => '14:50–15:20', 'name' => 'Dominek Dalma Lilla',                    'role' => '', 'institution' => '', 'talk_title' => 'A tanuláshoz való viszonyulás digitális oktatási környezetben: társadalmi attitűdök és jelentésstruktúrák vizsgálata Magyarországon', 'online' => true],
                    ['time' => '15:20–15:50', 'name' => 'Coffee break', 'break' => true],
                    ['time' => '15:50–16:10', 'name' => 'Sós Mihály',                             'role' => '', 'institution' => '', 'talk_title' => 'A drónfoci mint oktatási innovációs platform (Motiváció, kompetenciafejlesztés és intézményi implementáció)'],
                    ['time' => '16:10–16:30', 'name' => 'Csányiné Guszter Lídia',                 'role' => '', 'institution' => '', 'talk_title' => 'Robotika és kódolás alapjainak bevezetése a digitális kultúra tantárgyba tanulásban akadályozottak 3. évfolyamán'],
                    ['time' => '16:30–16:50', 'name' => 'Gulyás Zsuzsa',                          'role' => '', 'institution' => '', 'talk_title' => 'Az értelmezési intelligencia, mint a tanulás rejtett feltétele'],
                    ['time' => '16:50–17:10', 'name' => 'Pátrovics Botond István – Nagy Enikő',   'role' => '', 'institution' => '', 'talk_title' => 'Pneumatikus rendszerek vezérlési megvalósítása különböző PLC programozási módszerekkel'],
                    ['time' => '17:10–17:30', 'name' => 'Máté Bende',                             'role' => '', 'institution' => '', 'talk_title' => 'Darts Matek'],
                ],
            ],
        ],
    ],
    'speakers' => [
        [
            'name' => 'Päivi Häkkinen',
            'title' => 'Professor (Educational Technology)',
            'institution' => 'University of Jyväskylä, Finland',
            'image' => 'hakkinen_paivi.jpg',
            'image_position' => 'center top',
            'icon' => 'fa-solid fa-shield-halved',
            'image_scale' => '100%',
            'bio' => 'Päivi Häkkinen is a Professor of Educational Technology at the Finnish Institute for Educational Research, University of Jyväskylä, Finland. She leads the research area on technology-enhanced learning and, together with her research group, has established a systematic research strand focusing especially on the processes and outcomes of computer-supported collaborative learning. She has extensive experience as a principal investigator of research projects in the field, and she currently leads the research area Scalable Digital Solutions for Teaching and Learning within the EDUCA Flagship project funded by the Research Council of Finland. Her recent research interests also include the potential of AI in and for learning and collaboration. Professor Häkkinen has published actively in international journals and has participated in numerous scientific activities, including research training, research funding evaluation, conference committees, and editorial work. She has also contributed to public discussions on the digitalisation of education and the pedagogical design of technology-enhanced learning environments.',
        ],
        [
            'name' => 'Rikke Toft Nørgård',
            'title' => 'Associate Professor',
            'institution' => 'Danish School of Education, Aarhus University',
            'image' => 'rikke.jpg',
            'image_position' => 'center top',
            'image_scale' => 'cover',
            'bio' => 'Rikke Toft Nørgård is a Danish educational researcher and associate professor at the Danish School of Education at Aarhus University. Her research focuses on the future of higher education, digital pedagogy, and educational design. She explores the intersection of education, technology, play, and philosophy, with a particular emphasis on how learning processes can be transformed in creative and participatory ways. She is also actively involved in international research projects. For example, she serves as the coordinator of the EU-funded EPIC-WE project, which supports young people\'s cultural participation and creative expression through game development. Nørgård\'s work aims to develop innovative, digital, and playful forms of learning while rethinking future models of education.',
        ],
        [
            'name' => 'Márta Takács',
            'title' => 'Full University Professor',
            'institution' => 'Hungarian Language Teacher Training Faculty, Subotica',
            'image' => 'takacsmarta.jpg',
            'image_position' => 'center top',
            'image_scale' => '80%',
            'bio' => 'Dr. Márta Takács, full university professor at the Hungarian Language Teacher Training Faculty in Subotica, Doctor of Mathematical Sciences. She completed her studies at the Faculty of Science and Mathematics of the University of Belgrade, at Eötvös Loránd University in Budapest, and at the University of Novi Sad. Her work is characterized by a significant role both in Hungarian and cross-border scientific communities. In recognition of this, she received one of the prestigious awards of the Hungarian Academy of Sciences, the János Arany Award, as well as the Neumann Award. Her career is further marked by the fact that numerous international organizations in her field recognize her work. She is a respected member of the international scientific community dealing with the application of fuzzy-based systems. This is also supported by her membership in the IEEE and her role in the Hungarian Academy of Sciences in Vojvodina.',
        ],
        [
            'name' => 'Rita Ősz',
            'title' => 'Associate Professor, Researcher',
            'institution' => 'Dennis Gabor University',
            'image' => 'oszrita.jpg',
            'image_position' => 'center top',
            'bio' => 'She completed her studies in the fields of informatics and pedagogy. Her research focuses on the acquisition and processing of information from screens. Throughout her career, she has primarily been engaged in teaching IT-related subjects and in the effective application of ICT technologies in education, both domestically and internationally. Alongside her work, her activities in educational organization and research have been significant in her cross-border engagements.',
        ],
        [
            'name' => 'Krisztina Zimányi',
            'title' => 'Rector, training methodology expert',
            'institution' => 'Dennis Gabor University',
            'image' => 'zimanyi.jpg',
            'image_position' => 'center top',
            'image_scale' => '80%',
            'bio' => 'Dr. Krisztina Zimányi is an expert in educational methodology and the Rector of Dennis Gabor University, whose strategic and research work focuses on the integration of digital technologies and artificial intelligence into higher education. In her roles as an educator and leader, she places strong emphasis on the development of innovative learning environments, flexible, competency-based training formats, and e-learning solutions, with particular attention to how the relationship between classroom-based and online learning can be shaped to improve student learning outcomes. In her research and development projects, she examines the pedagogical added value of artificial intelligence applications in education—such as learning support systems, adaptive learning materials, and learning analytics—while also addressing their ethical and quality assurance implications. She is a frequent speaker at national and international conferences, where she presents how digital and methodological innovations are reshaping teaching roles, learning processes, and the strategic thinking of universities through practical examples, institutional best practices, and student feedback.',
        ],
    ],
];
