<?php
return [
    'section_title' => 'Plenáris előadók',
    'coming_soon' => 'Hamarosan...',
    'details' => 'Részletek',
    'program' => [
        'toggle_label' => 'FTFL május 21. Program',
        'schedule' => [
            ['time' => '09:15–10:00', 'title' => 'Regisztráció'],
            ['time' => '10:00–10:05', 'title' => 'Rektori köszöntő', 'speaker' => 'Zimányi Krisztina – Rektor, Gábor Dénes Egyetem'],
            ['time' => '10:05–11:45', 'title' => 'Plenáris előadások'],
        ],
        'plenary_talks' => [
            ['time' => '10:05–10:30', 'speaker' => 'Zimányi Krisztina – Ősz Rita', 'role' => 'Egyetemi docens – Rektor',   'institution' => 'Gábor Dénes Egyetem',                              'title' => 'Same Platform, Different Journeys: Talent, Mass and Micro-learning'],
            ['time' => '10:30–10:55', 'speaker' => 'Häkkinen, Päivi',                  'role' => 'Egyetemi tanár',              'institution' => 'Jyväskylä Egyetem – Finn Oktatáskutatási Intézet', 'title' => 'The Future of Learning and Collaboration in the Age of AI'],
            ['time' => '10:55–11:20', 'speaker' => 'Rikke Toft Nørgård',               'role' => 'Egyetemi docens',             'institution' => 'Aarhus Egyetem Dán Oktatási Iskola',               'title' => 'Between imagination and innovation: envisioning and engaging the future with hopepunk higher education'],
            ['time' => '11:20–11:45', 'speaker' => 'Takács Márta',                     'role' => 'Egyetemi tanár',              'institution' => 'Magyar Tannyelvű Tanítóképző Kar, Szabadka',        'title' => 'AI × Education: Everywhere, at Every Level – From Everyday Tools to Transformative Innovation in Learning'],
        ],
        'schedule_after' => [
            ['time' => '12:10–13:00', 'title' => 'Ebédszünet'],
            ['time' => '13:00–13:10', 'title' => 'A Gábor Dénes Emlékév lezárása – Dietz Ferenc és Fülöp Zsolt'],
            ['time' => '13:10–17:30', 'title' => 'Szekció-előadások (Kávészünet: 15:20–15:50)'],
        ],
        'sections_label' => 'Szekció-előadások és kerekasztal-beszélgetések',
        'sections' => [
            [
                'number'    => 1,
                'title'     => 'Horizon',
                'moderator' => 'Natália Kiss, Tomas Dragon',
                'room'      => 'Gábor Dénes előadó',
                'speakers'  => [
                    ['time' => '13:10–13:30', 'name' => 'Lucie Bryndova',           'role' => '', 'institution' => '', 'talk_title' => 'Assessing computational thinking in schools: Is it even possible to test the mind?'],
                    ['time' => '13:30–13:50', 'name' => 'Asmi Rusmanayanti',         'role' => '', 'institution' => '', 'talk_title' => 'Building Digital Competence for the Future of Learning: Insights from Pre-service and In-service EFL Teachers in Indonesia'],
                    ['time' => '13:50–14:10', 'name' => 'Péter Gyarmati',  'role' => '', 'institution' => '', 'talk_title' => 'Thoughts on Artificial Intelligence for Teachers'],
                    ['time' => '14:10–14:30', 'name' => 'László Murai',              'role' => '', 'institution' => '', 'talk_title' => 'We are EENJOY: Demonstrating ELTE\'s Experience-Based Platform for First-Year Induction with ARG Elements'],
                    ['time' => '14:30–14:50', 'name' => 'Veronika Csilla Derecskey', 'role' => '', 'institution' => '', 'talk_title' => 'Teacher Burnout and Re-Engagement in Hungarian Secondary EFL Education in Digitally Changing Educational Contexts'],
                    ['time' => '14:50–15:20', 'name' => 'Virág Vasas',               'role' => '', 'institution' => '', 'talk_title' => 'Breaking the „silent coder" stereotype: Information synthesis and professional visibility through elevator pitches in ICT education'],
                    ['time' => '15:20–15:50', 'name' => 'Kávészünet', 'break' => true],
                    ['time' => '15:50–16:10', 'name' => 'Gergely Kovács',            'role' => '', 'institution' => '', 'talk_title' => 'Teaching Beyond Reality: AI Avatars, Virtual Campuses and the Next Generation of Education'],
                    ['time' => '16:10–16:30', 'name' => 'Attila M. Wind',            'role' => '', 'institution' => '', 'talk_title' => 'Linguistic Characteristics of AI-Generated and Human-Produced Texts'],
                    ['time' => '16:30–16:50', 'name' => 'Dorota Czajkowska',         'role' => '', 'institution' => '', 'talk_title' => 'From Data to Understanding: Using Artificial Intelligence and Real-Time Economic Data in Public Finance and Economics Education', 'online' => true],
                    ['time' => '16:50–17:10', 'name' => 'Emmanuel Abruquah',         'role' => '', 'institution' => '', 'talk_title' => 'Human-in-the-Loop Communication: Repositioning Communication Pedagogy in AI-Driven Education', 'online' => true],
                    ['time' => '17:10–17:30', 'name' => 'Serbakov-Kovács Emese',   'role' => '', 'institution' => '', 'talk_title' => 'Artificial Intelligence in Language Teaching: Opportunities, Challenges, and Future Perspectives', 'online' => true],
                ],
            ],
            [
                'number'    => 2,
                'title'     => 'Nexus',
                'moderator' => 'Zimányi Krisztina',
                'room'      => 'Nemes Tihamér terem',
                'speakers'  => [
                    ['time' => '13:10–13:30', 'name' => 'Fodor Andrea-Nagy Enikő – Molnár György',                             'role' => '', 'institution' => '', 'talk_title' => 'A tanulás lehetőségeinek átalakulása digitálisan közvetített felsőoktatási környezetekben'],
                    ['time' => '13:30–13:50', 'name' => 'Buda András',                                                          'role' => '', 'institution' => '', 'talk_title' => 'Artificial intelligence and teachers in Debrecen', 'online' => true],
                    ['time' => '13:50–14:10', 'name' => 'Ollé János',                                                           'role' => '', 'institution' => '', 'talk_title' => 'Mesterséges intelligencia oktatástervezési munkafolyamatokban való felhasználásának kompetenciacsökkentő hatása'],
                    ['time' => '14:10–14:30', 'name' => 'Kocsó Edina',                                                          'role' => '', 'institution' => '', 'talk_title' => 'Tanulási környezet és lemorzsolódás – hallgatói percepciók egy intézményi vizsgálatban'],
                    ['time' => '14:30–14:50', 'name' => 'Papp-Danka Adrienn – Csikós Ádám Valentin – Jaczina Fanni – Tóth Katalin', 'role' => '', 'institution' => '', 'talk_title' => 'Digitális kompetenciák longitudinális vizsgálata a felsőoktatásban'],
                    ['time' => '14:50–15:20', 'name' => 'Tóth Renáta',                                                          'role' => '', 'institution' => '', 'talk_title' => 'A generatív mesterséges intelligencia rejtett használata az általános iskolában. Eltérések a tanulói használat és a pedagógusi észlelés között.'],
                    ['time' => '15:20–15:50', 'name' => 'Kávészünet', 'break' => true],
                    ['time' => '15:50–16:10', 'name' => 'Szontagh Pál Iván',                                         'role' => '', 'institution' => '', 'talk_title' => 'Felsőoktatás-pedagógiai kihívások a tömegesedő felsőoktatás korában'],
                    ['time' => '16:10–16:30', 'name' => 'Ladányi-Mészáros Judit',                                               'role' => '', 'institution' => '', 'talk_title' => 'A szociálpedagógia oktatástámogató szerepe a kortárs bántalmazás megelőzésében'],
                    ['time' => '16:30–16:50', 'name' => 'Molnárné László Andrea',                                           'role' => '', 'institution' => '', 'talk_title' => 'Mesterséges intelligencia mint hitéleti képzés: egy új interdiszciplináris modell kialakítása és tapasztalatai'],
                    ['time' => '16:50–17:10', 'name' => 'Kapusi Vanessza',                                                      'role' => '', 'institution' => '', 'talk_title' => 'Multimodális tanulási környezetek affektív hatásai hátrányos helyzetű tanulóknál', 'online' => true],
                    ['time' => '17:10–17:30', 'name' => 'Matlári Andrea',                                                       'role' => '', 'institution' => '', 'talk_title' => 'Az automatikus visszacsatolás szerepe a tanulásszabályozó döntésekben online tanulási környezetben'],
                ],
            ],
            [
                'number'    => 3,
                'title'     => 'Synergy',
                'moderator' => 'Ősz Rita',
                'room'      => 'Tréning terem',
                'speakers'  => [
                    ['time' => '13:10–13:30', 'name' => 'Kraszkó Zita',                          'role' => '', 'institution' => '', 'talk_title' => 'Beszéd és improvizáció – kreativitásfejlesztés és kommunikációs tréning a mesterséges intelligencia korában'],
                    ['time' => '13:30–13:50', 'name' => 'Korpics Márta Katalin – Méhes Tamás',   'role' => '', 'institution' => '', 'talk_title' => 'Az MI mint pedagógiai erőforrás: digitális kompetencia, oktatói szerepek és intézményi felelősség a felsőoktatásban'],
                    ['time' => '13:50–14:10', 'name' => 'Varga István',                           'role' => '', 'institution' => '', 'talk_title' => 'A szociálpedagógia átalakulása a digitális korszakban'],
                    ['time' => '14:10–14:30', 'name' => 'Papp Éva – Varga Tamás',                 'role' => '', 'institution' => '', 'talk_title' => 'Digitális ugródeszka: Komplex támogatási rendszer a Moodle alapú oktatáshoz'],
                    ['time' => '14:30–14:50', 'name' => 'Kis-Torma Olívia',                       'role' => '', 'institution' => '', 'talk_title' => 'Az algoritmikus tudatosság és a kritikai gondolkodás fejlesztése a virtuális entitások korában'],
                    ['time' => '14:50–15:20', 'name' => 'Dominek Dalma Lilla',                    'role' => '', 'institution' => '', 'talk_title' => 'A tanuláshoz való viszonyulás digitális oktatási környezetben: társadalmi attitűdök és jelentésstruktúrák vizsgálata Magyarországon', 'online' => true],
                    ['time' => '15:20–15:50', 'name' => 'Kávészünet', 'break' => true],
                    ['time' => '15:50–16:10', 'name' => 'Sós Mihály',                             'role' => '', 'institution' => '', 'talk_title' => 'A drónfoci mint oktatási innovációs platform (Motiváció, kompetenciafejlesztés és intézményi implementáció)'],
                    ['time' => '16:10–16:30', 'name' => 'Csányiné Guszter Lídia',                 'role' => '', 'institution' => '', 'talk_title' => 'Robotika és kódolás alapjainak bevezetése a digitális kultúra tantárgyba tanulásban akadályozottak 3. évfolyamán'],
                    ['time' => '16:30–16:50', 'name' => 'Gulyás Zsuzsa',                          'role' => '', 'institution' => '', 'talk_title' => 'Az értelmezési intelligencia, mint a tanulás rejtett feltétele'],
                    ['time' => '16:50–17:10', 'name' => 'Pátrovics Botond István – Nagy Enikő',   'role' => '', 'institution' => '', 'talk_title' => 'Pneumatikus rendszerek vezérlési megvalósítása különböző PLC programozási módszerekkel'],
                    ['time' => '17:10–17:30', 'name' => 'Máté Bende',                             'role' => '', 'institution' => '', 'talk_title' => 'Darts Matek'],
                ],
            ],
        ],
    ],
    'speakers' => [
        [
            'name' => 'Häkkinen, Päivi',
            'title' => 'Egyetemi tanár',
            'institution' => 'Jyväskylä Egyetem – Finn Oktatáskutatási Intézet',
            'image' => 'hakkinen_paivi.jpg',
            'image_position' => 'center top',
            'icon' => 'fa-solid fa-shield-halved',
            'image_scale' => '100%',
            'bio' => 'Päivi Häkkinen az oktatástechnológia professzora a Finn Oktatáskutatási Intézetben, a finnországi Jyväskylä Egyetemen. A technológiával támogatott tanulás kutatási terület vezetője, és kutatócsoportjával együtt egy szisztematikus kutatási irányt alakított ki, amely különösen a számítógéppel támogatott kollaboratív tanulás folyamataira és eredményeire összpontosít. Széles körű tapasztalattal rendelkezik kutatási projektek vezető kutatójaként ezen a területen, és jelenleg a Finn Kutatási Tanács által finanszírozott EDUCA Flagship projekt keretében a Skálázható digitális megoldások a tanítás és tanulás számára kutatási területet vezeti. Legutóbbi kutatási érdeklődési területei közé tartozik a mesterséges intelligencia tanulásban és együttműködésben betöltött szerepének vizsgálata is. Häkkinen professzor aktívan publikál nemzetközi folyóiratokban, és számos tudományos tevékenységben vett részt, többek között kutatóképzésben, kutatási pályázatok értékelésében, konferenciabizottságok munkájában és szerkesztői feladatok ellátásában. Emellett folyamatosan hozzájárul az oktatás digitalizációjáról és a technológiával támogatott tanulási környezetek pedagógiai tervezéséről szóló nyilvános szakmai diskurzusokhoz is.',
        ],
        [
            'name' => 'Rikke Toft Nørgård',
            'title' => 'Egyetemi docens',
            'institution' => 'Aarhus Egyetem Dán Oktatási Iskola',
            'image' => 'rikke.jpg',
            'image_position' => 'center top',
            'image_scale' => '80%',
            'bio' => 'Rikke Toft Nørgård dán oktatáskutató és egyetemi docens az Aarhusi Egyetem Dán Oktatási Iskolájában. Kutatásai elsősorban a felsőoktatás jövőjére, a digitális pedagógiára és az oktatás tervezésére irányulnak. Munkájában az oktatás, a technológia, a játékosság és a filozófia metszéspontját vizsgálja, különös figyelmet fordítva arra, hogyan alakíthatók át a tanulási folyamatok kreatív módon. Aktív résztvevője nemzetközi kutatási projektekben is, például az EU által támogatott EPIC-WE projekt koordinátora, amely a fiatalok kulturális részvételét és kreatív önkifejezését támogatja játékfejlesztésen keresztül. Nørgård munkássága az innovatív, digitális és játékos tanulási formák fejlesztésére, valamint a jövő oktatási modelljeinek újragondolására irányul.',
        ],
        [
            'name' => 'Takács Márta',
            'title' => 'Egyetemi tanár',
            'institution' => 'Magyar Tannyelvű Tanítóképző Kar, Szabadka',
            'image' => 'takacsmarta.jpg',
            'image_position' => 'center top',
            'image_scale' => '80%',
            'bio' => 'Dr. Takács Márta, a szabadkai Magyar Tannyelvű Tanítóképző Kar rendes egyetemi tanára, a matematika tudományok doktora. Tanulmányait a Belgrádi Egyetem Természettudományi-matematikai Karán, a budapesti Eötvös Loránd Tudományegyetemen, illetve az Újvidéki Egyetemen végezte. Munkásságára jellemző, hogy mind a magyar, mind a határon túli tudományos életben meghatározó szerepet tölt be. Ennek köszönhetően kapta meg az MTA egyik rangos elismerését az Arany János díjat, valamint a Neumann-díjat. Munkásságát az is fémjelzi, hogy a saját szakterületén számos nemzetközi szervezet ismeri el munkáját. Így a fuzzy alapú rendszerek alkalmazásával foglalkozó nemzetközi tudományos közösség elismert tagja. De ezt támasztja alá IEEE tagsága, illetve a Vajdasági Magyar Tudományos Akadémián betöltött szerepe is.',
        ],
        [
            'name' => 'Ősz Rita',
            'title' => 'Egyetemi docens, kutató',
            'institution' => 'Gábor Dénes Egyetem',
            'image' => 'oszrita.jpg',
            'image_position' => 'center top',
            'bio' => 'Tanulmányait az informatika és a pedagógia területén végezte. Kutatásai a képernyőről történő információ elsajátítás és feldolgozás témakörre fókuszálnak. Munkássága során leginkább informatikai tárgyak oktatásával és az IKT technológiák oktatásban történő hatékony alkalmazásával foglalkozott, mind hazai, mind nemzetközi területeken. A munkája mellett oktatásszervezési és kutatási tevékenységei meghatározóak voltak a határon túli tevékenységeiben.',
        ],
        [
            'name' => 'Zimányi Krisztina',
            'title' => 'Rektor, oktatásmódszertani szakértő',
            'institution' => 'Gábor Dénes Egyetem',
            'image' => 'zimanyi.jpg',
            'image_position' => 'center top',
            'image_scale' => '80%',
            'bio' => 'Dr. Zimányi Krisztina oktatásmódszertani szakértő, a Gábor Dénes Egyetem rektora, aki stratégiai és kutatói munkájában a digitális technológiák és a mesterséges intelligencia felsőoktatásba történő integrációjára fókuszál. Oktatói és vezetői szerepében kiemelt figyelmet fordít az innovatív tanulási környezetek, a rugalmas, kompetenciaalapú képzési formák és az e-learning megoldások fejlesztésére, különös tekintettel arra, hogyan alakítható át a tantermi és online tanulás kapcsolata a hallgatói tanulási eredmények javítása érdekében. Kutatási és fejlesztési projektjeiben a mesterséges intelligencia oktatási alkalmazásainak – például a tanulástámogató rendszereknek, az adaptív tananyagoknak és a tanulási analitikának – pedagógiai hozzáadott értékét vizsgálja, valamint ezek etikai és minőségbiztosítási kérdéseivel is foglalkozik. Rendszeres előadó hazai és nemzetközi konferenciákon, ahol gyakorlati példákon, intézményi jó gyakorlatokon és hallgatói visszajelzéseken keresztül mutatja be, miként formálják át a digitális és módszertani innovációk az oktatói szerepet, a tanulási folyamatokat és az egyetemek stratégiai gondolkodását.',
        ],
    ],
];
